### ISSUE TITLE
Possible to implement previews that don't overlap text?

### ISSUE THREAD

**Issue by lhagan** [mangecoeur/preview-inline#8]
I did a little digging into the API, but I couldn't figure out if Atom's architecture would allow for previews to be truly inline with the text -- i.e. not overlap the text that comes afterwards. Have you looked into this at all?

**Comment by mangecoeur** [comment]
I have looked into this, it doesn't seem that there is support in Atom for it yet, but there are some feature requests. The most promising approach would be to do the "reverse" of code folding - instead of collapsing several lines into a single on, add some "virtual" new lines that are not part of the text which can make some room for the preview. 

It might be possible to fake this by inserting a bunch of newlines into the document and removing them manually, but this is quite an ugly hack and i think it's bearable in its current state. I've vaguely considered putting previews in a side-pane but since you never know how wide the content will be i dong think this works any better.

**Comment by lhagan** [comment]
Thanks; really appreciate the detailed response.

**Comment by laughedelic** [comment]
Probably the new [block decorations](http://blog.atom.io/2016/02/03/introducing-block-decorations.html) are the solution here?

**Comment by mangecoeur** [comment]
Nice! I will wait for this to land in stable, looks very promising!

**Comment by mangecoeur** [comment]
Added block decoration support in version 1.0
