### ISSUE TITLE
LaTeX documents

### ISSUE THREAD

**Issue by fkjogu** [mangecoeur/preview-inline#9]
Is it supposed to be working inside LaTeX documents? I can't get it working.

It would make sense, right? ;)

**Comment by mangecoeur** [comment]
It should work if you select a region and run the preview command, assuming the text you selected is valid math. It can't otherwise guess which region corresponds to your formula (in markdown, latex segments are explicitly marked). I haven't really looked into Latex document support or the syntax highlighting packages, I suppose it might be possible to automatically detect "math" environments.

**Comment by fkjogu** [comment]
I played around again and found, the preview only works for me, when I've open the markdown preview window (from the package with the same name). But then it works as you described it also in LaTeX. Is this a bug?

**Comment by mangecoeur** [comment]
it could be some issue with the MathJax rendering - it's a bit hacky at the moment for various reasons. I'm waiting for a mathjax update which should improve this. I'm also enabling previews for LaTeX files by default

**Comment by etherealwinter** [comment]
You need to change the scope in the settings of preview-inline to: .text.tex.latex

**Comment by fkjogu** [comment]
Seems to be working now. Thx.
